version: '3'

services:
  helloworld:
    build: ./helloworld
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: helloworld
  
  consul:
    command: agent -dev -client=0.0.0.0
    image: consul:latest
    expose:
      - "8500"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  
  registrator:
    command:  consul://consul:8500
    image: gliderlabs/registrator:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    links:
      - consul
  
  lb:
    build: ./lb
    links:
      - consul
    ports:
      - "80:80"
    environment:
      CONSUL_URL: consul:8500
    volumes:
      - ./lb/consul-template:/etc/consul-template

networks:
  default:
    external:
      name: composetest_default
